def temp_recipe(food):
    return {"q": food, "from": 0, "to": 10, "more": True, "count": 120230, "hits": [
    {"recipe": {"uri": "http: //www.edamam.com/ontologies/edamam.owl#recipe_b79327d05b8e5b838ad6cfd9576b30b6",
                "label": f"{food} One",
                "image": "https: //www.edamam.com/web-img/e42/e42f9119813e890af34c259785ae1cfb.jpg",
                "source": "Serious Eats", "url": "http: //www.seriouseats.com/recipes/2011/12/chicken-vesuvio-recipe.html",
                "shareAs": "http: //www.edamam.com/recipe/chicken-vesuvio-b79327d05b8e5b838ad6cfd9576b30b6/chicken",
                "yield": 4.0, "dietLabels": ["Low-Carb"], "healthLabels": ["Peanut-Free", "Tree-Nut-Free"],
                "cautions": ["Sulfites"], "ingredientLines": ["1/2 cup olive oil", "5 cloves garlic, peeled",
                                                              "2 large russet potatoes, peeled and cut into chunks",
                                                              "1 3-4 pound chicken, cut into 8 pieces \
                                                              (or 3 pound chicken legs)",
                                                              "3/4 cup white wine",
                                                              "3/4 cup chicken stock",
                                                              "3 tablespoons chopped parsley",
                                                              "1 tablespoon dried oregano",
                                                              "Salt and pepper", "1 cup frozen peas, thawed"]}},
        {"recipe": {"uri": "http: //www.edamam.com/ontologies/edamam.owl#recipe_b79327d05b8e5b838ad6cfd9576b30b6",
                    "label": f"{food} Two",
                    "image": "https: //www.edamam.com/web-img/e42/e42f9119813e890af34c259785ae1cfb.jpg",
                    "source": "Serious Eats", "url": "http: //www.seriouseats.com/recipes/2011/12/chicken-vesuvio-recipe.html",
                    "shareAs": "http: //www.edamam.com/recipe/chicken-vesuvio-b79327d05b8e5b838ad6cfd9576b30b6/chicken",
                    "yield": 4.0, "dietLabels": ["Low-Carb"], "healthLabels": ["Peanut-Free", "Tree-Nut-Free"],
                    "cautions": ["Sulfites"], "ingredientLines": ["1/2 cup olive oil", "5 cloves garlic, peeled",
                                                                  "2 large russet potatoes, peeled and cut into chunks",
                                                                  "1 3-4 pound chicken, cut into 8 pieces \
                                                                  (or 3 pound chicken legs)",
                                                                  "3/4 cup white wine",
                                                                  "3/4 cup chicken stock",
                                                                  "3 tablespoons chopped parsley",
                                                                  "1 tablespoon dried oregano",
                                                                  "Salt and pepper", "1 cup frozen peas, thawed"]}},
            {"recipe": {"uri": "http: //www.edamam.com/ontologies/edamam.owl#recipe_b79327d05b8e5b838ad6cfd9576b30b6",
                        "label": f"{food} Three",
                        "image": "https: //www.edamam.com/web-img/e42/e42f9119813e890af34c259785ae1cfb.jpg",
                        "source": "Serious Eats", "url": "http: //www.seriouseats.com/recipes/2011/12/chicken-vesuvio-recipe.html",
                        "shareAs": "http: //www.edamam.com/recipe/chicken-vesuvio-b79327d05b8e5b838ad6cfd9576b30b6/chicken",
                        "yield": 4.0, "dietLabels": ["Low-Carb"], "healthLabels": ["Peanut-Free", "Tree-Nut-Free"],
                        "cautions": ["Sulfites"], "ingredientLines": ["1/2 cup olive oil", "5 cloves garlic, peeled",
                                                                      "2 large russet potatoes, peeled and cut into chunks",
                                                                      "1 3-4 pound chicken, cut into 8 pieces \
                                                                      (or 3 pound chicken legs)",
                                                                      "3/4 cup white wine",
                                                                      "3/4 cup chicken stock",
                                                                      "3 tablespoons chopped parsley",
                                                                      "1 tablespoon dried oregano",
                                                                      "Salt and pepper", "1 cup frozen peas, thawed"]}}
          ]}
